spring.application.name=biblioteca

#Puerto de la app
server.port =8080

#Configuracion de la base de datos H2 en archivo(persistente)
spring.datasource.url=jdbc:h2:file:./data/biblioteca
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

#Que hibernate actualice la base
spring.jpa.hibernate.ddl-auto=update

#Mostrar SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
